### ISSUE TITLE
EOFError in Flask-KVSession 0.6.2

### ISSUE THREAD

**Issue by ln2khanal** [mbr/flask-kvsession#42]
I am using Flask-KVSession (version 0.6.2). It does what it has to do. But when there are consecutive requests to webserver, following exception is repeated like a flood.

`2016-06-10_05:41:58.97125 2016-06-10 05:41:58 [29567] [ERROR] Error handling request
2016-06-10_05:41:58.97127 Traceback (most recent call last):
2016-06-10_05:41:58.97128   File "/usr/lib/pymodules/python2.7/gunicorn/workers/async.py", line 45, in handle
2016-06-10_05:41:58.97128     self.handle_request(listener, req, client, addr)
2016-06-10_05:41:58.97129   File "/usr/lib/pymodules/python2.7/gunicorn/workers/ggevent.py", line 151, in handle_request
2016-06-10_05:41:58.97129     super(GeventWorker, self).handle_request(*args)
2016-06-10_05:41:58.97129   File "/usr/lib/pymodules/python2.7/gunicorn/workers/async.py", line 93, in handle_request
2016-06-10_05:41:58.97130     respiter = self.wsgi(environ, resp.start_response)
2016-06-10_05:41:58.97130   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
2016-06-10_05:41:58.97140     return self.wsgi_app(environ, start_response)
2016-06-10_05:41:58.97141   File "<flask_app_deploy_file.py>", line 18, in __call__
2016-06-10_05:41:58.97142   File "/usr/lib/python2.7/dist-packages/werkzeug/contrib/fixers.py", line 144, in __call__
2016-06-10_05:41:58.97142     return self.app(environ, start_response)
2016-06-10_05:41:58.97142   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in wsgi_app
2016-06-10_05:41:58.97143     ctx.push()
2016-06-10_05:41:58.97143   File "/usr/lib/python2.7/dist-packages/flask/ctx.py", line 321, in push
2016-06-10_05:41:58.97152     self.session = self.app.open_session(self.request)
2016-06-10_05:41:58.97161   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 825, in open_session
2016-06-10_05:41:58.97162     return self.session_interface.open_session(self, request)
2016-06-10_05:41:58.97162   File "/usr/lib/pymodules/python2.7/flask_kvsession/__init__.py", line 159, in open_session
2016-06-10_05:41:58.97163     current_app.kvsession_store.get(sid_s)
2016-06-10_05:41:58.97163 EOFError
2016-06-10_05:41:58.97187 ERROR: Error handling request`

I posted same question on [http://stackoverflow.com/questions/37745600/eoferror-in-flask-kvsession-0-6-2](url) but nobody replied.
I can't use Flask-KVSession due to this bug.

**Comment by mbr** [comment]
Which backend are you using?

**Comment by ln2khanal** [comment]
I have flat filesystem used. I mean `FilesystemStore`

**Comment by mbr** [comment]
You seem to have an underlying IO problem. FilesystemStores are not suitable for any real web application, as they do not allow concurrency. You will have to add a locking mechanism or switch to a different backend.

Try using something like Redis or memcache instead.

**Comment by ln2khanal** [comment]
Hhmm... that is a work around. Thanks for replying.
