### ISSUE TITLE
new simplekv versions no longer compatible

### ISSUE THREAD

**Issue by petriggles** [mbr/flask-kvsession#43]
https://github.com/mbr/simplekv/releases/tag/0.11.0

```App 217 stderr: [2017-09-13 18:47:04,325] ERROR in app: Exception on /login/ [GET]
App 217 stderr: Traceback (most recent call last):
App 217 stderr:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
App 217 stderr:     response = self.full_dispatch_request()
App 217 stderr:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
App 217 stderr:     return self.finalize_request(rv)
App 217 stderr:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1632, in finalize_request
App 217 stderr:     response = self.process_response(response)
App 217 stderr:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1858, in process_response
App 217 stderr:     self.save_session(ctx.session, response)
App 217 stderr:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 924, in save_session
App 217 stderr:     return self.session_interface.save_session(self, session, response)
App 217 stderr:   File "/usr/local/lib/python2.7/dist-packages/flask_kvsession/__init__.py", line 193, in save_session
App 217 stderr:     store.put(session.sid_s, data, ttl)
App 217 stderr:   File "/usr/local/lib/python2.7/dist-packages/simplekv/decorator.py", line 73, in put
App 217 stderr:     self._dstore.put(self._map_key(key), *args, **kwargs))
App 217 stderr:   File "/usr/local/lib/python2.7/dist-packages/simplekv/decorator.py", line 104, in _map_key
App 217 stderr:     self._check_valid_key(key)
App 217 stderr:   File "/usr/local/lib/python2.7/dist-packages/simplekv/__init__.py", line 190, in _check_valid_key
App 217 stderr:     raise ValueError('%r is not a unicode string' % key)```

**Comment by mbr** [comment]
Seems like a regression, I'm on it.

**Comment by mbr** [comment]
Someone already filed it as https://github.com/mbr/simplekv/issues/57. I'll see if fixes are made, otherwise, I will pin the dependency on a specific simplekv version.

**Comment by petriggles** [comment]
Sounds good. I thought I read that they intended some amount of backwards incompatibility, but it looks like they're working on a fix

**Comment by hachreak** [comment]
Hi @mbr,
I saw that the new simplekv version that fix the problem has been released (0.11.2).
Could you please increase minimum version of simplekv and release a new version of flask-kvsession?
This would be great! :smile: 
If you want I can create a PR.
